FROM jenkins/jenkins:lts

USER root

# Add jenkins user to docker group
RUN groupadd -g 977 docker && usermod -aG docker jenkins


# Install Docker and Ansible via apt
RUN apt-get update && \
    apt-get install -y \
    docker.io \
    ansible \
    && rm -rf /var/lib/apt/lists/*

# Verify installations
RUN docker --version && \
    ansible-playbook --version

USER jenkins
